#ifndef KCSA_FILTER_H
#define KCSA_FILTER_H

#include "types.h"
#include "sim.h"

/*
 * ══════════════════════════════════════════════════════════════════════════
 * KCSA SELECTIVITY FILTER — the real thing.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * WHAT THIS REPLACES, AND WHY IT MATTERS
 *
 * The previous KcsA model was a hand-placed array of eight carbonyl
 * oxygens held on harmonic position restraints, with a poly-alanine
 * chain behind it. That is not the potassium channel: the real KcsA
 * selectivity filter is the pentapeptide TVGYG, and the Thr76 and Tyr79
 * side chains that the poly-alanine model replaced with methyl groups
 * are the residues the channel's selectivity is actually built from.
 * Every number the old model produced was therefore a property of a
 * constructed cage rather than of KcsA.
 *
 * This module builds the filter from DEPOSITED ATOMIC COORDINATES.
 *
 *   Source      : PDB 1K4C, chain C, the Streptomyces lividans KcsA
 *                 - Fab complex at high K+ (MacKinnon et al., Science
 *                 280, 1061 (1998); Doyle et al. Nature 280, 105
 *                 (1998)). 1K4C is in this repository as
 *                 s10_1K4C.pdb.
 *   Segment     : residues 75-79 = THR-VAL-GLY-TYR-GLY, the signature
 *                 sequence. (1K4C numbers the construct one lower than
 *                 the canonical Thr76-Val77-Gly78-Tyr79-Gly80.)
 *   Subunits    : KcsA is a homotetramer and the crystallographic
 *                 asymmetric unit contains ONE copy, so the other three
 *                 are generated by the C4 rotation about the pore axis.
 *                 The operation was DERIVED, not assumed: rotating the
 *                 single copy by 90/180/270 degrees about the axis
 *                 through the ion column reproduces a coordination
 *                 number of exactly 8 at every deposited K+ site, which
 *                 is the textbook KcsA result and is what makes the
 *                 symmetry identification unambiguous. A wrong axis
 *                 gives 2, not 8.
 *
 * VALIDATION OF THE RECOVERED GEOMETRY
 *
 *   C=O            1.219 - 1.242 A   (deposited; textbook 1.23)
 *   C(i)-N(i+1)    1.327 - 1.335 A   (deposited; textbook 1.33)
 *   CB-OG1         1.436 A           (deposited; textbook 1.43)
 *   K+-O at site 2 2.721 A x4, 2.833 A x4, CN = 8, square antiprism
 *   K+-O spread across all four sites: 2.688 - 3.082 A
 *
 * The four 8-oxygen sites, outermost first, and the oxygens that form
 * them — this is the canonical KcsA picture and it emerged from the
 * coordinates rather than being assumed:
 *
 *   site 4  THR75 OG1  (2.88 A x4)  +  THR75 backbone O  (2.94 A x4)
 *   site 3  THR75 backbone O (2.69-2.71 A x4) + VAL76 O (2.84-2.86 A x4)
 *   site 2  GLY77 backbone O (2.72 A x4) + VAL76 O (2.83 A x4)
 *   site 1  TYR78 backbone O (2.78-2.80 A x4) + GLY79 O... no:
 *            TYR78 backbone O (2.78-2.80 A x4) + GLY77 O (3.06-3.08 A x4)
 *
 * Two things a hand-built model would never have produced, and both
 * are load-bearing:
 *
 *   1. The innermost gate is the Thr75 SIDE-CHAIN hydroxyl (OG1), not
 *      a backbone carbonyl. In the poly-alanine model this atom did not
 *      exist, so the most important single ligand in the filter was
 *      missing entirely.
 *   2. GLY79's backbone oxygen sits 4.82 A off the pore axis and does
 *      NOT coordinate any ion. GLY79 is part of the signature motif
 *      but is not a filter ligand. Any model that assumed all five
 *      residues contribute a carbonyl to the ion path would be wrong.
 *
 * TYR78's phenol hydroxyl is 9.2 A from the nearest K+: it points into
 * the pore wall, not the pore. Tyr79 (canonical numbering) is a gating
 * residue, not a selectivity residue, and building it as a ligand would
 * have been a mistake.
 *
 * SCOPE — WHAT THIS IS NOT
 *
 * This is a rigid, fixed-charge model of the real filter. It has no
 * side-chain flexibility, no bulk solvent, no membrane potential, and
 * its partial charges are a documented ff99-based approximation (see
 * kcsa_filter.c). Building the correct geometry fixes the question
 * "is this KcsA?" — it does not by itself make the free energy
 * quantitative. See kcsa_site_binding() for the two ingredients that
 * do carry the K/Na discrimination, one of which is not a force-field
 * term at all.
 *
 * See also KCSA_HYDRATION_*, below, and the readme's KcsA section.
 */

/* Heavy atoms + constructed amide H + the C-terminal OXT of one TVGYG
 * segment, in a frame whose z axis is the pore axis and whose origin is
 * the crystal translation applied in kcsa_filter.c. */
#define KCSA_FILTER_ATOMS 41
#define KCSA_FILTER_BONDS 41

/*
 * Build the filter. `n_subunits` copies are placed, related by the
 * tetramer's C4 rotation about the pore axis; use 4 for the real
 * channel. `origin` translates the whole assembly.
 *
 * Returns the index of the first atom, or -1 on failure.
 */
int kcsa_build_filter(Simulation *sim, Vec3 origin, int n_subunits);

/*
 * Number of filter oxygens per subunit that actually coordinate the ion
 * path: THR75 O, THR75 OG1, VAL76 O, GLY77 O, TYR78 O = 5. GLY79 O is
 * built (it is part of the motif) but sits off-axis and is not one.
 */
#define KCSA_FILTER_LIGAND_O_PER_SUBUNIT 5

/*
 * The four 8-oxygen ion sites along the pore, z in the filter frame.
 * Recovered from the four K+ positions in 1K4C; see the header.
 */
int kcsa_ion_sites(int n_out, Vec3 *out);

/*
 * Coordination statistics of a point against the assembled filter:
 *   n_within  = oxygens within `cutoff` of the point
 *   mean_r    = mean distance to those oxygens
 * Returns the count, or -1 on bad input.
 */
int kcsa_coord_stats(const Simulation *sim, int filter_first,
                     int n_subunits, Vec3 point, double cutoff,
                     double *mean_r);

/* Eight-coordinate Shannon effective ionic radius in Angstrom (Shannon 1976).
 * Full-audit M3: was six-coordinate (K 1.38, Na 1.02); filter is CN=8 so
 * VIII values are correct (K 1.51, Na 1.18, Li 0.92, Rb 1.61, Cs 1.74). */
double kcsa_cation_radius(int Z);

/*
 * Give an alkali cation its physical size as a Lennard-Jones site.
 *
 * A point charge cannot select: in a symmetric cage it sits at the centre
 * for K+ and Na+ alike and feels identical electrostatics. The radius is
 * what makes the site discriminate, and it is taken from tabulated
 * ionic radii, NOT fitted to reproduce a selectivity result:
 *
 *   r(K+) 1.51 A (VIII)  r(Na+) 1.18 A (VIII)  r(O) 1.40 A
 *   => preferred contact 2.91 A (K–O) and 2.58 A (Na–O)
 *
 * sigma is fixed by requiring the ion–O LJ minimum to sit at that contact.
 * The solve is in two steps, because the mixed sigma is not the contact:
 * with Lorentz–Berthelot, sigma_ionO = (sigma_ion + sigma_O)/2, so putting
 * 2^(1/6) sigma_ionO at the contact fixes sigma_ionO, and then sigma_ionO
 * fixes sigma_ion by inversion. With sigma_O = LJ_AMBER_O_SIGMA (2.959922 A,
 * the AMBER R* 1.6612 converted) that gives
 *
 *   sigma_ionO 2.5925 A (K+), 2.2985 A (Na+)   ->  minimum at 2.91 / 2.58 A
 *   sigma_ion  2.2251 A (K+), 1.6371 A (Na+)
 *
 * Full-audit M3: previous values 2.4767/2.1560 and 1.9935/1.3520 used
 * six-coordinate contacts 2.78/2.42 A. Updated for VIII radii; asserted in
 * tests/test_regression.c so header and implementation cannot drift.
 *
 * AUDIT FIX D2: this comment used to claim sigma 1.888 A (K+) and 1.246 A
 * (Na+). Those numbers are wrong on both counts. They come from mixing
 * against a bare r(O) = 1.40 A where sigma is asked for, which is a
 * radius, not a sigma; and they were never checked against the code. The
 * values above are computed from the constants actually used in
 * kcsa_set_ion_radius() and are asserted in tests/test_regression.c, so
 * this comment and the implementation cannot drift apart again.
 *
 * One shared epsilon (0.05 kcal/mol on the ion–O pair) is used for every
 * alkali, so the comparison has no per-ion strength available to it -
 * only the size ratio. The per-ion epsilon the code back-solves is
 * 0.01190 kcal/mol on the ion site (0.05^2/0.21; full-audit M8 corrects the
 * previous 0.00300 which was 4x low), which is a mixing artifact and not a
 * physical parameter; do not read it as one.
 */
void kcsa_set_ion_radius(Simulation *sim, int ion, int Z);

/*
 * Measured single-ion hydration free energy in kJ/mol on the TATB-based
 * absolute scale (Marcus 1991, Faraday Trans. 87, 2995). This is the
 * term that actually decides
 * K+/Na+ selectivity in the real filter, and it is a bulk thermodynamic
 * measurement rather than anything a vacuum force field can produce.
 * Returns 0.0 for an ion with no tabulated value.
 */
double kcsa_hydration_free_energy_kJmol(int Z);

/* Cost of desolvating the ion to enter the site, in eV (positive).
 * 1 eV = 96.48533212... kJ/mol (N_A*e/1000). K+ costs 3.061 eV,
 * Na+ 3.786 eV, so K+ enters 0.726 eV cheaper (AUDIT FIX N1: the
 * earlier -322/-454 set was hydration ENTHALPY and made this 1.368 eV).
 * That difference is larger than the electrostatic
 * preference of the smaller Na+ cation, and it is why KcsA is
 * potassium-selective. */
double kcsa_dehydration_cost_eV(int Z);

/*
 * One ion at one site against the rigid filter.
 * e_inter = minimised intermolecular energy (eV)
 * e_total = e_inter + the dehydration cost (eV)
 * AUDIT FIX D5: this comment described a `frozen[]` parameter. There is no
 * frozen[] parameter and there never was one in this signature - it
 * describes an earlier design that kept a caller-supplied freeze mask. The
 * filter is instead frozen by construction: kcsa_build_filter() documents
 * that it deliberately does NOT rebuild angles, and kcsa_site_binding
 * runs with use_bonds = use_angles = use_dihedrals = 0, so no bonded term
 * can move a filter atom. The mask exists as a local inside
 * kcsa_site_binding (call it `frozen`, sized sim->num_atoms) and is
 * internally allocated; the simulation is capped at 512 atoms, which a
 * 41-atom-per-subunit filter is well inside.
 *
 * Returns the ion's atom index, or -1 on failure.
 */
int kcsa_site_binding(Simulation *sim, int filter_first, int n_subunits,
                      int ion_Z, Vec3 site, int n_steps,
                      double *e_inter, double *e_total);

/* Flexible-filter tethers (opt-in for KcsA drift fix): anchor every
 * C-alpha in the built filter to its deposited position with spring k.
 * Backbone breathes around the deposited geometry instead of being
 * frozen by construction; k=0.5 eV/A^2 gives ~0.09 A RMS at 50 K.
 * Returns tether count or -1 on bad input. Record path does not call
 * this (rigid stays the record). */
int kcsa_add_calpha_tethers(Simulation *sim, int filter_first,
                            int n_subunits, double k);

/* Side-chain hydrogen completion (the blatant missing piece).
 *
 * The deposited table carries heavy atoms + amide H + OXT only: 26 H
 * per subunit (104 per channel) are absent — Thr/Val methyls, Gly CH2,
 * Tyr ring + OH, Thr OG1-H. Heavy carbons carry fudged neutralizing
 * charges while their H LJ bulk is missing, so the walls have no
 * steric Pauli barrier and bare OG1/O (-0.65) overbind. This appends
 * all 26 H per subunit with ideal geometry + AMBER charges/LJ
 * (HC +0.06, HA +0.15, HO +0.42) and re-neutralizes each residue by
 * uniform carbon shift (exact neutrality preserved). Opt-in: record
 * path stays 41 atoms; flexible path calls this. Returns H count
 * (104 for tetramer) or -1. With ions + zero-strain bonds/geometric
 * angles + tethers + Langevin, the filter HOLDS (CN 8->8); empty it
 * collapses (CN 8->1) — the 1K4D inactivated split, not an artefact. */
int kcsa_add_hydrogens(Simulation *sim, int filter_first, int n_subunits);

#endif /* KCSA_FILTER_H */
